local Settings = {
	
	infos = {
		["Version"] = "0.0.1",         		-- version be like
		["Update"] = "09-10-2026",     		-- To know if this is the real version
		["Creator"] = "LightOfTheWar", 		-- Cant change this bcs there is MIT license
		["GameName"] = "GAMENAME", 	   		-- Your Game Name
		["INTRO"] = [[.

██████╗ ██╗     ███╗   ██╗███████╗
██╔══██╗██║     ████╗  ██║██╔════╝
██████╔╝██║     ██╔██╗ ██║███████╗
██╔══██╗██║     ██║╚██╗██║╚════██║
██║  ██║███████╗██║ ╚████║███████║
╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚══════╝
                        
MIT license
Available on GitHub
            
]]
	}
	
}

return Settings